[versions]
androidAnnotation = "1.2.0"
moshi = "1.13.0"
javaX = "1"
kotlinPoet = "1.8.0"
ksp = "1.7.0-1.0.6"
kotlin = "1.7.0"
agp = "7.2.0"
junit5 = "5.8.2"
detekt = "1.20.0"
jacoco = "0.8.8"
jsonParser = "0.1.2"
androidBuildTool = "32.0.0"
androidCompile = "32"
targetSdk = "32"
minSdk = "21"
rxjava = "3.1.1"
rxjavaAndroid = "3.0.0"
coroutine = "1.5.0"
androidxTest-junit = "1.1.3"
androidxTest-core = "1.4.0"
roboletric = "4.5.1"
android-compat = "1.3.1"

# test
test-powermock = "2.0.9"
test-junit4 = "4.1.3"
test-mockito = "3.12.4"
test-mockitoKotlin = "3.2.0"

[libraries]
common-moshi = { module = "com.squareup.moshi:moshi", version.ref = "moshi" }
common-moshiCompiler = { module = "com.squareup.moshi:moshi-kotlin-codegen", version.ref = "moshi" }
common-androidAnnotation = { module = "androidx.annotation:annotation", version.ref = "androidAnnotation" }
common-javaX = { module = "javax.inject:javax.inject", version.ref = "javaX" }
common-kotlinPoet = { module = "com.squareup:kotlinpoet", version.ref = "kotlinPoet" }
common-kspProcessingApi = { module = "com.google.devtools.ksp:symbol-processing-api", version.ref = "ksp" }
common-rxjava = { module = "io.reactivex.rxjava3:rxjava", version.ref = "rxjava" }
common-rxjavaAndroid = { module = "io.reactivex.rxjava3:rxandroid", version.ref = "rxjavaAndroid" }
common-coroutine = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutine" }
common-recyclerview = { module = "androidx.recyclerview:recyclerview", version= "1.2.0" }
common-databinding-runtime = {module = "androidx.databinding:databinding-runtime", version.ref="agp"}
common-databinding-common = {module = "androidx.databinding:databinding-common", version.ref="agp"}

androidx-compat = {module="androidx.appcompat:appcompat", version.ref="android.compat"}

# plugin
plugin-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
plugin-ksp = { module = "com.google.devtools.ksp:com.google.devtools.ksp.gradle.plugin", version.ref = "ksp" }
plugin-agp = { module = "com.android.tools.build:gradle", version.ref = "agp" }
plugin-detekt = { module = "io.gitlab.arturbosch.detekt:detekt-gradle-plugin", version.ref = "detekt" }
plugin-jacoco = { module = "org.jacoco:org.jacoco.core", version.ref = "jacoco" }

# test
test-junit5 = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit5" }
test-junit4 = { module = "junit:junit", version.ref = "test.junit4" }
test-jupiterEngine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit5" }
test-jupiterVintage = { module = "org.junit.vintage:junit-vintage-engine", version.ref = "junit5" }
test-mockito = { module = "org.mockito:mockito-core", version.ref = "test.mockito" }
test-mockitoKotlin = { module = "org.mockito.kotlin:mockito-kotlin", version.ref = "test.mockitoKotlin" }
test-turbine = { module = "app.cash.turbine:turbine", version = "0.7.0" }
test-coroutineTest = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutine" }
test-robolectric-core = {module ="org.robolectric:robolectric", version.ref="roboletric"}
test-robolectric-shadow = {module ="org.robolectric:shadowapi", version.ref="roboletric"}
test-powermock-core = {module ="org.powermock:powermock-core", version.ref="test.powermock"}
test-powermock-junit4 = {module ="org.powermock:powermock-module-junit4", version.ref="test.powermock"}
test-powermock-mockito = {module ="org.powermock:powermock-api-mockito2", version.ref="test.powermock"}

test-androidxTest-core = { module = "androidx.test:core", version.ref = "androidxTest-core" }
test-androidxTest-runner = { module = "androidx.test:runner", version.ref = "androidxTest-core" }
test-androidxTest-junit = { module = "androidx.test.ext:junit", version.ref = "androidxTest-junit" }

# verify
verify-detektFormatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detekt" }

# android-alatn
jsonParser-api = { module = "com.github.android-alatan.jsonparser:json-parser-api", version.ref = "jsonParser" }
jsonParser-impl = { module = "com.github.android-alatan.jsonparser:json-parser", version.ref = "jsonParser" }
jsonParser-factory = { module = "com.github.android-alatan.jsonparser:moshi-adapter-factory", version.ref = "jsonParser" }
jsonParser-ksp = { module = "com.github.android-alatan.jsonparser:moshi-adapter-factory-ksp", version.ref = "jsonParser" }


[plugins]
#agp = { id = "com.android.tools.build", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
androidApp = { id = "com.android.application", version.ref = "agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }